import type { AgentDefinition, SkillDefinition, Workflow } from "./types.ts";

export const MARKER = "generated by novel-harness — do not edit; run `novel sync`";
export const GENERATED_HEADER = `<!-- ${MARKER} -->`;
export const GENERATED_HEADER_LINE = `// ${MARKER}`;

export function markdownHeader(): string {
  return `${GENERATED_HEADER}\n`;
}

export function tomlHeader(): string {
  return `# ${MARKER}\n`;
}

/** Adapters that use `$ARGUMENTS` (Claude Code, opencode). */
export function dollarArguments(workflow: Workflow): string {
  return workflow.body.replaceAll("{{args}}", "$ARGUMENTS").trimEnd();
}

/** Adapters that keep `{{args}}` (Gemini CLI). */
export function braceArguments(workflow: Workflow): string {
  return workflow.body.trimEnd();
}

export interface CommandFrontmatter {
  description: string;
  argumentHint?: string;
}

export function markdownCommand(workflow: Workflow): string {
  const lines = ["---", `description: ${yamlScalar(workflow.description)}`];
  if (workflow.argumentHint) {
    lines.push(`argument-hint: ${yamlScalar(workflow.argumentHint)}`);
  }
  lines.push("---", "", GENERATED_HEADER, "", dollarArguments(workflow), "");
  return lines.join("\n");
}

/** Minimal YAML scalar quoting for short single-line values. */
export function yamlScalar(value: string): string {
  if (/^[A-Za-z0-9][A-Za-z0-9 .,'`()/_-]*$/.test(value) && !value.includes(": ")) {
    return value;
  }
  return JSON.stringify(value);
}

/** TOML basic string (JSON escaping is a valid subset of TOML basic strings). */
export function tomlString(value: string): string {
  return JSON.stringify(value);
}

export function geminiCommand(workflow: Workflow, notes: string[] = []): string {
  const lines = [
    tomlHeader().trimEnd(),
    `description = ${tomlString(workflow.description)}`,
    `prompt = ${tomlString(braceArguments(workflow))}`,
    "",
  ];
  for (const note of notes) lines.push(`# ${note}`);
  return lines.join("\n");
}

export function instructionsFile(heading: string, instructions: string, notes: string[]): string {
  const parts = [markdownHeader(), instructions.trimEnd(), ""];
  if (notes.length > 0) {
    parts.push(`## Agent notes (${heading})`, "");
    for (const note of notes) parts.push(`- ${note}`);
    parts.push("");
  }
  return parts.join("\n");
}

export function markdownAgent(agent: AgentDefinition): string {
  const lines = ["---", `description: ${yamlScalar(agent.description)}`, "mode: subagent"];
  if (agent.permission) {
    lines.push("permission:");
    for (const [key, value] of Object.entries(agent.permission)) {
      if (typeof value === "string") {
        lines.push(`  ${key}: ${value}`);
      } else {
        lines.push(`  ${key}:`);
        for (const [glob, action] of Object.entries(value)) {
          lines.push(`    ${JSON.stringify(glob)}: ${action}`);
        }
      }
    }
  }
  lines.push("---", "", GENERATED_HEADER, "", agent.prompt.trimEnd(), "");
  return lines.join("\n");
}

export function claudeAgent(agent: AgentDefinition): string {
  const lines = ["---", `name: ${agent.name}`, `description: ${yamlScalar(agent.description)}`];
  if (agent.tools && agent.tools.length > 0) {
    lines.push(`tools: ${agent.tools.join(", ")}`);
  }
  lines.push("---", "", GENERATED_HEADER, "", agent.prompt.trimEnd(), "");
  return lines.join("\n");
}

export function markdownSkill(skill: SkillDefinition): string {
  const lines = [
    "---",
    `name: ${skill.name}`,
    `description: ${yamlScalar(skill.description)}`,
    "---",
    "",
    GENERATED_HEADER,
    "",
    skill.body.trimEnd(),
    "",
  ];
  return lines.join("\n");
}
