import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { claudeAdapter } from "../../../src/core/adapters/claude.ts";
import { geminiAdapter } from "../../../src/core/adapters/gemini.ts";
import { agentsMdAdapter } from "../../../src/core/adapters/agents-md.ts";
import { opencodeAdapter } from "../../../src/core/adapters/opencode.ts";
import { syncAdapters } from "../../../src/core/adapters/sync.ts";
import { DEFAULT_CONFIG } from "../../../src/core/project/config.ts";
import { INSTRUCTIONS, defaultWorkflows } from "../../../src/workflows/index.ts";
import { makeBundle } from "../../helpers.ts";
import { SAMPLE_INPUT } from "../../sample.ts";

const sampleInput = SAMPLE_INPUT;

function find(files: { path: string; content: string }[], path: string) {
  return files.find((file) => file.path === path);
}

describe("markdown adapters", () => {
  test("agents-md renders AGENTS.md with instructions", () => {
    const files = agentsMdAdapter.render(sampleInput);
    const agents = find(files, "AGENTS.md");
    expect(agents?.content).toContain("Do good work.");
    expect(agents?.content).toContain("generated by novel-harness");
  });

  test("opencode and agents-md agree on AGENTS.md byte for byte", () => {
    const agents = find(agentsMdAdapter.render(sampleInput), "AGENTS.md");
    const opencode = find(opencodeAdapter.render(sampleInput), "AGENTS.md");
    expect(opencode?.content).toBe(agents?.content);
  });

  test("opencode renders slash commands with $ARGUMENTS", () => {
    const files = opencodeAdapter.render(sampleInput);
    const command = find(files, ".opencode/command/draft.md");
    expect(command?.content.startsWith("---\n")).toBe(true);
    expect(command?.content).toContain("description: Draft a scene");
    expect(command?.content).toContain('argument-hint: "<scene id>"');
    expect(command?.content).toContain("Draft `$ARGUMENTS` now.");
    expect(command?.content).not.toContain("{{args}}");
  });

  test("claude renders commands and CLAUDE.md", () => {
    const files = claudeAdapter.render(sampleInput);
    expect(find(files, "CLAUDE.md")?.content).toContain("Do good work.");
    expect(find(files, ".claude/commands/draft.md")?.content).toContain("$ARGUMENTS");
  });

  test("gemini renders TOML commands with {{args}}", () => {
    const files = geminiAdapter.render(sampleInput);
    const command = find(files, ".gemini/commands/draft.toml");
    expect(command?.content).toContain('description = "Draft a scene"');
    expect(command?.content).toContain("Draft `{{args}}` now.");
    expect(command?.content).toContain("prompt = ");
  });
});

describe("sync", () => {
  test("writes, is idempotent, detects conflicts, and prunes", async () => {
    const root = await makeBundle({});
    const input = { workflows: defaultWorkflows(), instructions: INSTRUCTIONS };

    const first = await syncAdapters(root, DEFAULT_CONFIG, input);
    expect(first.written).toHaveLength(71);
    expect(first.written).toContain("AGENTS.md");
    expect(first.written).toContain(".claude/commands/draft.md");
    expect(first.written).toContain(".opencode/agent/researcher.md");
    expect(first.written).toContain(".opencode/skill/novel-recon/SKILL.md");
    expect(first.written).toContain(".opencode/tools/novel_fetch.ts");
    expect(first.written).toContain(".opencode/plugin/novel-guard.ts");
    expect(first.written).toContain(".claude/agents/skeptic.md");
    expect(first.written).toContain(".opencode/command/skeptic.md");
    expect(first.written).toContain(".opencode/command/recon.md");
    expect(first.written).toContain(".gemini/commands/outline.toml");
    expect(existsSync(join(root, ".novel/manifest.json"))).toBe(true);

    const second = await syncAdapters(root, DEFAULT_CONFIG, input);
    expect(second.unchanged).toHaveLength(71);
    expect(second.written).toHaveLength(0);

    const draftPath = join(root, ".claude/commands/draft.md");
    await writeFile(draftPath, `${await readFile(draftPath, "utf8")}\nmanual\n`, "utf8");
    const conflicted = await syncAdapters(root, DEFAULT_CONFIG, input);
    expect(conflicted.conflicts).toContain(".claude/commands/draft.md");
    expect(await readFile(draftPath, "utf8")).toContain("manual");

    await writeFile(draftPath, await readFile(join(root, ".opencode/command/draft.md"), "utf8"), "utf8");
    const config = { ...DEFAULT_CONFIG, targets: DEFAULT_CONFIG.targets.filter((t) => t !== "claude") };
    const pruned = await syncAdapters(root, config, input);
    expect(pruned.removed).toContain("CLAUDE.md");
    expect(pruned.removed).toContain(".claude/commands/draft.md");
    expect(existsSync(join(root, ".claude"))).toBe(false);
  });
});
