import { describe, expect, test } from "bun:test";
import { mkdtemp, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { claudeAdapter } from "../../../src/core/adapters/claude.ts";
import { opencodeAdapter } from "../../../src/core/adapters/opencode.ts";
import { AGENTS, artifactKit, SKILLS } from "../../../src/core/adapters/kit/index.ts";
import { defaultWorkflows } from "../../../src/workflows/index.ts";
import { SAMPLE_INPUT } from "../../sample.ts";

const input = { ...SAMPLE_INPUT, ...artifactKit() };

function find(files: { path: string; content: string }[], path: string) {
  return files.find((file) => file.path === path);
}

describe("agent definitions", () => {
  test("researcher is read-only with web tools", () => {
    const researcher = AGENTS.find((agent) => agent.name === "researcher");
    expect(researcher?.permission?.edit).toBe("deny");
    expect(researcher?.tools).toContain("WebFetch");
    expect(researcher?.tools).not.toContain("Edit");
    expect(researcher?.prompt).toContain("Never state a fact from memory");
    expect(researcher?.prompt).toContain("attested");
  });

  test("skeptic never verifies unsupported claims", () => {
    const skeptic = AGENTS.find((agent) => agent.name === "skeptic");
    expect(skeptic?.tools).not.toContain("Edit");
    expect(skeptic?.prompt).toContain("unsupported");
    expect(skeptic?.prompt).toContain("Never mark a concept verified");
  });
});

describe("specialized drafting agents", () => {
  test("story-planner is read-only, bash-allowed, web-denied", () => {
    const agent = AGENTS.find((entry) => entry.name === "story-planner");
    expect(agent?.permission?.edit).toBe("deny");
    expect(agent?.permission?.bash).toBe("allow");
    expect(agent?.permission?.webfetch).toBe("deny");
    expect(agent?.prompt).toContain("novel context --story");
    expect(agent?.prompt).toContain("threads --dangling");
  });

  test("scene-drafter scopes edits to story/**, elsewhere ask", () => {
    const agent = AGENTS.find((entry) => entry.name === "scene-drafter");
    expect(agent?.permission?.edit).toEqual({ "story/**": "allow", "*": "ask" });
    expect(agent?.prompt).toContain("--so-far");
    expect(agent?.prompt).toContain("/scene-check");
  });

  test("scene-checker is read-only with bash", () => {
    const agent = AGENTS.find((entry) => entry.name === "scene-checker");
    expect(agent?.permission?.edit).toBe("deny");
    expect(agent?.prompt).toContain("knowledge bleed");
  });

  test("knowledge-keeper edits only story/knowledge.md", () => {
    const agent = AGENTS.find((entry) => entry.name === "knowledge-keeper");
    expect(agent?.permission?.edit).toEqual({ "story/knowledge.md": "allow", "*": "deny" });
    expect(agent?.prompt).toContain("Since");
  });

  test("continuity-checker checks knowledge bleed and future references", () => {
    const agent = AGENTS.find((entry) => entry.name === "continuity-checker");
    expect(agent?.prompt).toContain("--so-far");
    expect(agent?.prompt).toContain("foreshadow");
  });
});

describe("skill definitions", () => {
  test("recon skill carries the three claim states", () => {
    const recon = SKILLS.find((skill) => skill.name === "novel-recon");
    expect(recon?.body).toContain("attested");
    expect(recon?.body).toContain("inferred");
    expect(recon?.body).toContain("unknown");
  });

  test("all skills have descriptions with trigger words", () => {
    for (const skill of SKILLS) {
      expect(skill.description.length).toBeGreaterThan(20);
    }
  });
});

describe("kit rendering", () => {
  test("opencode renders agents and skills with frontmatter", () => {
    const files = opencodeAdapter.render(input);
    const agent = find(files, ".opencode/agent/researcher.md");
    expect(agent?.content.startsWith("---\n")).toBe(true);
    expect(agent?.content).toContain("mode: subagent");
    expect(agent?.content).toContain("edit: deny");
    const skill = find(files, ".opencode/skill/novel-harness/SKILL.md");
    expect(skill?.content).toContain("name: novel-harness");
    const fetch = find(files, ".opencode/tools/novel_fetch.ts");
    expect(fetch?.content).toContain("tool(");
    expect(fetch?.content).toContain("generated by novel-harness");
    const query = find(files, ".opencode/tools/novel_query.ts");
    expect(query?.content).toContain('novel", "query"');
  });

  test("claude renders agents with tool allow-lists", () => {
    const files = claudeAdapter.render(input);
    const agent = find(files, ".claude/agents/researcher.md");
    expect(agent?.content).toContain("name: researcher");
    expect(agent?.content).toContain("tools: Read, Grep, Glob, WebFetch, WebSearch");
    const skill = find(files, ".claude/skills/novel-drafting/SKILL.md");
    expect(skill?.content).toContain("name: novel-drafting");
    expect(files.some((file) => file.path.startsWith(".claude/tools/"))).toBe(false);
  });

  test("novel_context tool supports --story and --so-far", () => {
    const files = opencodeAdapter.render(input);
    const ctx = find(files, ".opencode/tools/novel_context.ts");
    expect(ctx?.content).toContain("--story");
    expect(ctx?.content).toContain("--so-far");
    expect(ctx?.content).toContain("soFar");
  });

  test("opencode renders the guard plugin", () => {
    const files = opencodeAdapter.render(input);
    const plugin = find(files, ".opencode/plugin/novel-guard.ts");
    expect(plugin?.content).toContain('"tool.execute.after"');
    expect(plugin?.content).toContain("novel validate");
    expect(plugin?.content).toContain("last-validate.json");
    expect(plugin?.content).toContain("apply_patch");
    expect(plugin?.content).toContain("patchText");
  });

  test("guard plugin detects story files in write, edit, and apply_patch args", async () => {
    const files = opencodeAdapter.render(input);
    const plugin = find(files, ".opencode/plugin/novel-guard.ts");
    const dir = await mkdtemp(join(tmpdir(), "novel-guard-"));
    const path = join(dir, "novel-guard.ts");
    await writeFile(path, plugin?.content ?? "", "utf8");
    const loaded = (await import(path)) as {
      touchedStoryPath: (tool: string, args: Record<string, unknown>) => string | undefined;
    };
    const touched = loaded.touchedStoryPath;

    expect(touched("write", { filePath: "story/characters/x.md" })).toBe("story/characters/x.md");
    expect(touched("edit", { filePath: "README.md" })).toBeUndefined();
    expect(
      touched("apply_patch", {
        patchText:
          "*** Begin Patch\n*** Update File: story/chapters/ch-01.md\n@@\n-old\n+new\n*** End Patch",
      }),
    ).toBe("story/chapters/ch-01.md");
    expect(
      touched("apply_patch", {
        patchText: "*** Begin Patch\n*** Add File: src/app.ts\n+x\n*** End Patch",
      }),
    ).toBeUndefined();
    expect(
      touched("apply_patch", {
        patchText: "*** Begin Patch\n*** Move to: story/chapters/two.md\n*** End Patch",
      }),
    ).toBe("story/chapters/two.md");
  });
});

describe("workflow prompts", () => {
  test("recon and skeptic workflows reference the kit", () => {
    const workflows = defaultWorkflows();
    const recon = workflows.find((workflow) => workflow.name === "recon")?.body ?? "";
    const skeptic = workflows.find((workflow) => workflow.name === "skeptic")?.body ?? "";
    expect(recon).toContain("researcher");
    expect(recon).toContain("novel_fetch");
    expect(recon).toContain("skeptic");
    expect(recon).toContain("attested");
    expect(recon).toContain("inferred");
    expect(skeptic).toContain("supported");
    expect(skeptic).toContain("unsupported");
  });
});
